name: Postman Collection Workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

  schedule:
    - cron: 30 02 * * *
    - cron: 00 14 * * *

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install nodejs & npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install newman & htmlextra globally  
        run:  npm install -g newman && npm install -g newman-reporter-htmlextra 

      - name: Run postman collection with newman 
        run: |
            newman run 'InWarrenty flow Copy.postman_collection.json' \
            -e phoenix_URL.postman_environment.json \
            -d testdata.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export ./newman/index.html

      - name: Newman Report 
        if: always()
        uses: actions/upload-artifact@v7.0.1 
        with:
          name: Newman Report 
          path: newman/*.html
          
      - name: Creating GithubPage branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: newman/

      - name: send email notification
        if: always()
        uses: dawidd6/action-send-mail@v16
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMIAL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject:  phoenix inwarrenty flow execution notifcation
          to: ramitasambyal2023@gmail.com
          from: ramitasambyal@gmail.com
          body: |
                Hi,
                Phoneix inwarrenty flow completetd . Report has been published and url is
                https://ramita123.github.io/Phoenix-InWarranty-Flow-Collection-Files/
          
          
        
          
        
        
       
